import './globals.css';
import {Inter} from 'next/font/google';
import ThemeProvider from './providers/theme_provider';
import dynamic from 'next/dynamic';

const inter = Inter({subsets: ['latin']});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const DynamicContextProvider = dynamic(
	() => import('./providers/theme_provider').then((mod) => mod.default),
	{
		ssr: true,
	}
);

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<DynamicContextProvider>
				<body className={inter.className}>{children}</body>
			</DynamicContextProvider>
		</html>
	);
}
